inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/spring'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  Enabled: false
