# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github:
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

development:
  <<: *default
  secret_key_base: 5d10d12c35414291a5c70ddc6b2d99c1eb54b23f934477962f867332c89dd871c261ba3a049383dd63e5e1a7c105e8a05b187009cefb35d40bf2aaa7a7db524f

test:
  <<: *default
  secret_key_base: cc84114746013c72fee28760c8fe022726a248629feae504dccd037fb87ce42b2d01f5576dff3009445683377835874a88f164aff405ffdc30d1b5885dd46446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
